platform :ios, '8.0'
use_frameworks!

target 'SDWebImageAPNGCoder_Example' do
  pod 'SDWebImageAPNGCoder', :path => '../'

  target 'SDWebImageAPNGCoder_Tests' do
    inherit! :search_paths

    pod 'Specta'
  	pod 'Expecta'
  end
end
